version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost

  postgres:
    image: postgres:15-alpine
    hostname: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: travelsignals
      POSTGRES_USER: travelsignals
      POSTGRES_PASSWORD: travelsignals
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: travelsignals-backend
    ports:
      - "8080:8080"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      QUARKUS_HTTP_PORT: 8080
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/travelsignals
      QUARKUS_DATASOURCE_USERNAME: travelsignals
      QUARKUS_DATASOURCE_PASSWORD: travelsignals
      QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION: update
    depends_on:
      - kafka
      - postgres
    volumes:
      - ../backend:/app
    working_dir: /app

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: travelsignals-frontend
    ports:
      - "8081:80"
    depends_on:
      - backend
    environment:
      VITE_API_BASE_URL: http://localhost:8080

volumes:
  postgres_data:
